### ISSUE TITLE
Why another extensions library?

### ISSUE THREAD

**Issue by vasily-kirichenko** [huwman/FnSharp.Core#1]
Have you seen ExtCore and  FSharpx.Extras? They have everything this repo has and much, much more.

**Comment by huwman** [comment]
Hi Vasily,

Sorry for the late response.
While I don't want to create confusion or fragmentation in the F# community, my focus has not been nearly as broad as those who created the repos you've mentioned. I have enjoyed creating and using the repo I created as it suits my needs and conventions. Also I focused on building C# support and interop for the Result Type.

I look forward to F# having a Result type and hopefully the related functions builtin soon, I think this will reduce fragmentation and improve interop between F# code bases.
