### ISSUE TITLE
Please rename this library

### ISSUE THREAD

**Issue by dsyme** [huwman/FnSharp.Core#2]
Hi @huwman 

Could you please rename this library to follow the [guidelines](http://fsharp.github.io/2014/09/19/fsharp-libraries.html)?  In particular, since this is not a canonical extensions library, it would be _much_ better if you use a name like "SuperExt" or "MyExtensions" or "Fuzz" rather than "FSharp.Core.Extras".

For example, "ExtCore" is a similar extensions library.

Once you rename the library, please unlist all the nuget packages at https://www.nuget.org/packages/FSharp.Core.Extra/

Many thanks
Don Syme, F# Language Designer

**Comment by dsyme** [comment]
Hi @huwman,

Have you made progress on renaming the library please?  

Thanks
Don

**Comment by huwman** [comment]
Hi Don,

Sorry, only just saw your message. Will rename, was following a practice
common within the ELM community, by adding the .extra. But I understand the
potential for confusion.

Thanks.

On Tue, 19 Apr 2016 20:45 Don Syme, <notifications@github.com> wrote:

> Hi @huwman <https://github.com/huwman>,
>
> Have you made progress on renaming the library please?
>
> Thanks
>
>
> Don
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/huwman/FSharp.Core.Extra/issues/2#issuecomment-212064574>
>
-- 

Regards,
Huw Simpson

**Comment by dsyme** [comment]
Thank you! :)

**Comment by huwman** [comment]
All nuget packages have now been unlisted. Renamed to FnSharp.Core, it might still be a little close to FSharp, hopefully not too much so. However it is a name I've used for some time, and a complement to your creation, F# :)

**Comment by dsyme** [comment]
Great, thanks!!!
